sudo: required
services:
  - docker

before_install:
  - docker build -t aayushadhikari/docker-react -f Dockerfile.dev .

script:
  - docker run aayushadhikari/docker-react npm run test -- --coverage
